// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDL4bJdh41lj_ApyHr4DJm17TtoxPU5lis",
      authDomain: "trackmybills-941d7.firebaseapp.com",
      databaseURL: "https://trackmybills-941d7-default-rtdb.firebaseio.com",
      projectId: "trackmybills-941d7",
      storageBucket: "trackmybills-941d7.firebasestorage.app",
      messagingSenderId: "917075874864",
      appId: "1:917075874864:web:eb9dd0fc10c08c7ed089f5",
      measurementId: "G-LQ1G1JCEBX"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYy7qJU1l-UgnbsriytudnIQYibgoksw',
    appId: '1:917075874864:android:0a281bd0e2c8c337d089f5',
    messagingSenderId: '605928868545',
    projectId: 'trackmybills-941d7',
    databaseURL: 'https://trackmybills-941d7-default-rtdb.firebaseio.com',
    storageBucket: 'trackmybills-941d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8pJgqpUHjppuELNaHAiaqKs9ZiUr1PI',
    appId: '1:917075874864:ios:ac7cbb1dcb13f620d089f5',
    messagingSenderId: '605928868545',
    projectId: 'trackmybills-941d7',
    databaseURL: 'https://trackmybills-941d7-default-rtdb.firebaseio.com',
    storageBucket: 'trackmybills-941d7.firebasestorage.app',
    androidClientId: '917075874864-1tsgfp9eiiqgpq85g6nsnt7rsmf3kpm4.apps.googleusercontent.com',
    iosClientId: '917075874864-bm4pn9ghlosvk0les0rkeacjd492mvte.apps.googleusercontent.com',
    iosBundleId: 'com.wpjp.xpensly',
  );

}